-- 1 display the customer name , product name ,quantity and order date for every order 
select c.customer_name,
		p.product_name ,
	    oi.quantity,
        o.order_date 
 from customers c  join orders o on c.customer_id=o.customer_id
 join order_items oi  on o.order_id = oi.order_id 
 join  products p on oi.product_id = p.product_id ;
 
 -- 2 find the total revenue generated by the company 
 select sum(total_amount) from orders;
 
 -- 3  display all products whose stock is less than 20 
 select product_name , stock from products where stock < 20 ;
 
 -- 4  display  customers whose payment status is peniding 
  select c.customer_id,
          c.customer_name,
          o.order_id,
          p.payment_method,
          p.payment_status 
	from customers c join orders o on c.customer_id= o.customer_id 
    join payments p on o.order_id =p.order_id where p.payment_status="pending";

-- 5 which product generated highest  revenue 
select p.product_id , p.product_name, sum(p.price*oi.quantity) as revenue from products p join order_items oi on p.product_id = oi.product_id
group by p.product_name,p.product_id  order by revenue desc limit 1 ;

-- 6 display the top 3 customers based on total purchase amount
select  c.customer_id,c.customer_name , sum(o.total_amount) as total_purchase from customers c join orders o on c.customer_id = o.customer_id
group by c.customer_id,c.customer_name order by total_purchase desc limit 3 ;

-- 7 display order_id ,customer name , payment method and payment status 
select c. customer_name  , o.order_id  ,p.payment_status , p.payment_method  from customers c join orders o  on c.customer_id = o.customer_id 
join payments p  on o.order_id = p.order_id ;

-- 8 find customers who purchased electronics products 
select c.customer_id , c.customer_name ,p.product_name,p.category from customers c join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id =oi.order_id join products p on oi.product_id = p.product_id  where p.category = "electronics";

-- 9 display category wise total revenue 
 select p.category ,sum(p.price*oi.quantity) as total_revenue from products p join order_items oi on p.product_id = oi.product_id 
 group by p.category;
 
 -- 10 display the complete order report with customer name , product name , catrgory , quantity, price , total(price* quantity ),order date , payment status ,payment method 
 select c.customer_name ,
			p.product_name ,
			p.category ,
			oi.quantity , 
			p.price,
			p.price*oi.quantity as total_price ,
			o.order_date,
			py.payment_method,
			py.payment_status
from customers c join orders o on c.customer_id = o.customer_id 
join payments py on o.order_id = py.order_id 
join order_items oi on o.order_id = oi.order_id
join products p on oi.product_id =p.product_id ; 